DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('doppelganger/', include('doppelganger.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGO_BLOG/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

DJANGO_BLOG/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model) :
    title = models.CharField(max_length=30)
    title_en = models.CharField(max_length=30)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=30)
    watch_grade = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.CharField(max_length=100)
    description = models.TextField()

DJANGO_BLOG/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def index(request):
    #movies = Movie.objects.all()[::-1]
    movies = Movie.objects.order_by('-pk')
    return render(request, 'movies/index.html', {'movies':movies})

def new(request):
    return render(request, 'movies/new.html')

def create(request):
    movie = Movie()
    movie.title = request.POST.get('title')
    movie.title_en = request.POST.get('title_en')
    movie.audience = request.POST.get('audience')
    movie.open_date = request.POST.get('open_date')
    movie.genre = request.POST.get('genre')
    movie.score = request.POST.get('score')
    movie.poster_url = request.POST.get('poster_url')
    movie.description = request.POST.get('description')
    movie.save()
    return redirect('movies:index')

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    return render(request, 'movies/detail.html', {'movie':movie})

DJANGO_BLOG/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    
</body>
</html>

DJANGO_BLOG/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}DETAIL{% endblock %}

{% block body %}
<h1 class="text-center">DETAIL</h1>
<div class="w-50 p-3 text-center" style="background-color:#eee; margin:auto;">
    <p class="h3">{{ movie.title }}</p>
    <p class="h5">{{ movie.title_en }}</p>
    <hr>
    <p class="h5">Audience : {{ movie.audience }}</p>
    <p class="h5">Open Date : {{ movie.open_date }}</p>
    <p class="h5">Genre : {{ movie.genre }}</p>
    <p class="h5">Score : {{ movie.score }}</p>
    <img src="{{ movie.poster_url }}" alt="" width="100%">
    <p class="h6">{{ movie.description }}</p>
    <a href="{% url 'movies:index' %}" class="btn btn-secondary">뒤로가기</a>
</div>
{% endblock %}

DJANGO_BLOG/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block title %}INDEX{% endblock %}

{% block body %}
    <h1 class="text-center">MOVIE LIST</h1>
    <hr>
    <div class="w-50 p-3 text-center" style="background-color:#eee; margin:auto;">
        <a href="{% url 'movies:new' %}" class="btn btn-danger">NEW</a>
        <hr>
        {% for movie in movies %}
            <h3><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></h3>
            <h5>{{ movie.score }}</h5>
            <hr>
        {% endfor %}
    </div>
    
    <hr>

{% endblock %}

DJANGO_BLOG/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block title %}CREATE{% endblock%}

{% block body %}
<h1 class="text-center">CREATE</h1>
<hr>
<div class="w-50 p-3 text-center" style="background-color:#eee; margin:auto;">
    <form action="/movies/create/" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Title</span>
            </div>
            <input type="text" class="form-control" name="title">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Title(EN)</span>
            </div>
            <input type="text" class="form-control" name="title_en">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Audience</span>
            </div>
            <input type="number" class="form-control" name="audience">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Open Date</span>
            </div>
            <input type="date" class="form-control" name="open_date">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Genre</span>
            </div>
            <input type="text" class="form-control" name="genre">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Grade</span>
            </div>
            <input type="text" class="form-control" name="watch_grade">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">Score</span>
            </div>
            <input type="number" class="form-control" name="score" step="0.01">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text">URL</span>
            </div>
            <input type="text" class="form-control" name="poster_url">
        </div>

        <div class="form-group">
            <textarea class="form-control" name="description" rows="3">Discription</textarea>
        </div>

        <button type="submit" class="btn btn-primary">등록하기</button>
        <a href="{% url 'movies:index' %}" type="submit" class="btn btn-secondary">뒤로가기</a>
    </form>
</div>
{% endblock %}