DJANGO_MOVIE/django_movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

DJANGO_MOVIE/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_id>/score/<int:score_id>/delete', views.score_delete, name='score_delete'),
    path('<int:movie_id>/score/new', views.score_new, name='score_new'),
    path('<int:movie_id>/delete/', views.delete, name='delete'),
    path('<int:movie_id>/update/', views.update, name='update'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

DJANGO_MOVIE/movies/models.py
from django.db import models


class Genre(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'


class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre_id = models.ForeignKey(Genre, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.title}'


class Score(models.Model):
    id = models.IntegerField(primary_key=True)
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie_id = models.ForeignKey(Movie, on_delete = models.CASCADE)

    def __str__(self):
        return f'<Score({self.id}) : content({self.content}), score({self.score}), movie_id({self.movie_id})>'

DJANGO_MOVIE/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Score
from .models import Genre

def index(request):
    # articles = Article.objects.all()
    # articles = Article.objects.order_by('-pk')
    movies = Movie.objects.all()[::-1]
    return render(request, 'movies/index.html', {'movies': movies})

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')
        movie = Movie(title=title, title_en=title_en, audience=audience, open_date=open_date, genre=genre, watch_grade=watch_grade, score=score, poster_url=poster_url, description=description)
        movie.save()
        
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/new.html')

def detail(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    scores = movie.score_set.order_by('-pk')
    return render(request, 'movies/detail.html', {'movie': movie, 'scores': scores})

def delete(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else: 
        return recirect('movies:detail', movie.pk)

def update(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/edit.html', {'movie': movie})

def score_new(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    if request.method == "POST":
        score = Score()
        score.content = request.POST.get('content')
        score.score = request.POST.get('score')
        score.movie_id = movie
        score.save()
    return redirect('movies:detail', movie_id)

def score_delete(request, movie_id, score_id):
    if request.method == "POST":
        score = Score.objects.get(pk=score_id)
        score.delete()
    return redirect('movies:detail', movie_id)

DJANGO_MOVIE/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}Document</title>
    
    <style>
        *{margin: 0;padding: 0;}
        h1{margin: 50px 0;}
        .movie_list{width: 100%;}
        .row div{margin-bottom: 30px;}
        .movie_list p{text-align: center;}
        .movie_list p.title a{color: #000;font-weight: 500;}
    </style>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

</body>
</html>

DJANGO_MOVIE/movies/templates/movies/create.html
{% extends 'articles/base.html' %}

{% block title %}CREATE{% endblock %}
{% block body %}
    <h1 class='text-center'>성공적으로 작성되었습니다.</h1>
{% endblock %}

DJANGO_MOVIE/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}DETAIL{% endblock %}
{% block body %}
    <h1 class='text-center'>Movie 상세정보</h1>
    <hr>
    <p><img src="{{ movie.poster_url }}" alt="{{ movie.title }}" style="width: 100px;"></p>
    <p>{{ movie.title }}</p>
    <p>장르 : {{ movie.genre_id.name }}</p>
    <p>평점 : {{ movie.score }}점</p>
    <p>관객수 : {{ movie.audience }}명</p>
    <p><b>줄거리</b><br>{{ movie.description }}</p>
    <hr>
    <a href="{% url 'movies:index' %}" class="btn btn-info" style="display: inline;">목록</a>
    <a href="{% url 'movies:update' movie.pk %}" class="btn btn-primary" style="display: inline;">수정</a>
    <form action="{% url 'movies:delete' movie.pk %}" onclick="return confirm('R U Sure..??')" method="POST" style="display: inline;">
        {% csrf_token %}
        <button class="btn btn-danger" style="display: inline;">삭제</button>
    </form>
    <hr>
    <form action="{% url 'movies:score_new' movie.id %}" method="POST">
        {% csrf_token %}
        한줄평: <input type="text" name="content">
        평점: <input type="number" name="score">
        <button class="btn btn-success">입력</button>
    </form>
    <hr>
    <h3>한줄평</h3><br>
    {% for score in scores %}
    <ul>
        <li>한줄평: {{ score.content }} / 평점: {{ score.score }}
            <form action="{% url 'movies:score_delete' movie.id score.id %}" method="POST" style="display: inline">
                {% csrf_token %}
                <button class="btn btn-warning btn-sm">삭제</button>
            </form>
        </li>
    </ul>
    {% empty %}
    <p>한줄평이 아직 없습니다. 한줄평을 작성해 주세요.</p>
    {% endfor %}
    <!--<a href="{% url 'movies:delete' movie.pk %}">[삭제]</a><br>-->
{% endblock %}

DJANGO_MOVIE/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}

{% block title %}EDIT{% endblock %}
{% block body %}
    <h1 class='text-center'>Movie 상세정보 수정</h1>
    <form action="" method="POST">
        {% csrf_token %}
        제목: <input type="text" name="title" value="{{ movie.title }}"><br>
        관객수: <input type="number" name="audience" value="{{ movie.audience }}"><br>
        포스터 URL: <input type="text" name="poster_url" value="{{ movie.poster_url }}"><br>
        설명: <textarea name="description" id="" cols="30" rows="10">{{ movie.description }}</textarea>
        <input type="submit" value="수정">
    </form>
    <hr>
    <a href="{% url 'movies:detail' movie.pk %}">[뒤로가기]</a>
{% endblock %}

DJANGO_MOVIE/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block title %}CRUD{% endblock %}
{% block body %}
    <h1 class='text-center'>Movies</h1>
    <a href="{% url 'movies:create' %}" class="btn btn-info btn-lg btn-block">영화 등록</a>
    <hr>

    <div class="movie_list row">
    {% for movie in movies %}
        <div class="col-xs-6 col-sm-4 col-sm-4">
            <p><a href="{% url 'movies:detail' movie.pk %}"><img src="{{ movie.poster_url }}" alt="{{ movie.title }}" class="img-thumbnail img-responsive"></a></p>
            <p class="title"><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

DJANGO_MOVIE/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block title %}NEW{% endblock %}
{% block body %}
    <h1 class='text-center'>Movie 등록</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="inputTitle">제목</label>
            <input type="text" name="title" class="form-control" id="inputTitle" placeholder="제목을 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputTitleEn">제목(영문)</label>
            <input type="text" name="title_en" class="form-control" id="inputTitleEn" placeholder="제목(영문)을 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputAudience">관객수</label>
            <input type="text" name="audience" class="form-control" id="inputAudience" placeholder="관객수를 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputOpenDate">개봉일</label>
            <input type="date" name="open_date" class="form-control" id="inputOpenDate" placeholder="개봉일을 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputGenre">장르</label>
            <input type="text" name="genre" class="form-control" id="inputGenre" placeholder="장르를 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputWatchGrade">관람등급</label>
            <input type="text" name="watch_grade" class="form-control" id="inputWatchGrade" placeholder="관람등급을 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputScore">평점</label>
            <input type="text" name="score" class="form-control" id="inputScore" placeholder="평점을 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputPosterURL">포스터 URL</label>
            <input type="text" name="poster_url" class="form-control" id="inputPosterURL" placeholder="포스터 이미지의 경로를 입력하세요">
        </div>
        <div class="form-group">
            <label for="inputPosterURL">줄거리</label>
            <textarea name="description" class="form-control" rows="3"></textarea>
        </div>

        <input type="submit" class="btn btn-info btn-lg btn-block">
    </form>
    <hr>
    <a href="{% url 'movies:index' %}" class="btn btn-default btn-lg btn-block">목록</a>
{% endblock %}