DJANGO_BLOG/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('quit/', views.quit, name='quit'),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
]

DJANGO_BLOG/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/update/', views.update, name='update'),
    path('<int:article_id>/delete/', views.delete, name='delete'),
    path('<int:article_id>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    #path('new/', views.new),
    path('', views.index, name="index"),
]

DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('doppelganger/', include('doppelganger.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGO_BLOG/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

DJANGO_BLOG/articles/models.py
from django.db import models
from django.conf import settings
# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill, Thumbnail

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True) #이미지 없는 게시글의 경우 NULL값 인정
    # image = ProcessedImageField(
    #     upload_to = 'articles/images',      # 저장 위치(MEDIA_ROOT/articles/images)
    #     processors = [Thumbnail(200,300)],  # 처리할 작업 목록
    #     format = 'JPG',                     # 저장 포맷
    #     options = {'quality' : 90},         # 추가 옵션
    # )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    
    def __str__(self):
        return f'{self.id}번 글 - {self.title} : {self.content}'

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str___(self):
        return f'<Article({self.article_id}) : Comment({self.id})> - {self.content}'

DJANGO_BLOG/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    #articles = Article.objects.all()[::-1]
    articles = Article.objects.order_by('-pk')
    return render(request, 'articles/index.html', {'articles':articles})

def new(request):
    return render(request, 'articles/new.html')

@login_required
def create(request):
    # 1.
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 2.
    # article = Article(title=title, content=content)
    # article.save()

    if request.method == 'POST':    
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        return render(request, 'articles/new.html')

def detail(request, article_id):
    article = Article.objects.get(pk=article_id)
    comments = article.comment_set.all()
    return render(request, 'articles/detail.html', {'article':article, 'comments':comments})

def delete(request, article_id):
    article = Article.objects.get(pk=article_id)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else :
        return redirect('article:detail', article.pk)

@login_required
def update(request, article_id):
    article = Article.objects.get(pk=article_id)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.image = request.FILES.get('image')
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        return render(request, 'articles/edit.html', {'article':article})

def comment_create(request, article_id):
    article = Article.objects.get(pk=article_id)
    if request.method == 'POST':
        comment = Comment()
        comment.content = request.POST.get('content')
        comment.article = article
        comment.save()
    #     return redirect('articles:detail', article.id)
    # else:
    #     return redirect('articles:detail', article.id)
    return redirect('articles:detail', article_id)
    
def comment_delete(request, article_id, comment_id):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_id)
        comment.delete()
    return redirect('articles:detail', article_id)

DJANGO_BLOG/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
        <h1>Hello! {{ user.username }} </h1>
        <a href="{% url 'accounts:edit' %}"><button class="btn btn-success btn-sm">회원정보 수정</button></a>
        <a href="{% url 'accounts:change_password' %}"><button class="btn btn-success btn-sm">비밀번호 변경</button></a>
        <form action="{% url 'accounts:logout' %}" method="POST" style='display:inline'>
            {% csrf_token %}
            <button class="btn btn-success btn-sm">로그아웃</button>
        </form>
        <form action="{% url 'accounts:quit' %}" method="POST" style='display:inline'>
            {% csrf_token %}
            <button class='btn btn-secondary btn-sm'>회원탈퇴</button>
        </form>
        {% else %}
        <h1>Hello! Stranger</h1>
        <a href="{% url 'accounts:signup' %}"><button class="btn btn-success btn-sm">회원가입</button></a>
        <a href="{% url 'accounts:login' %}"><button class="btn btn-success btn-sm">로그인</button></a>
        {% endif %}
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    
</body>
</html>

DJANGO_BLOG/articles/templates/articles/create.html
{% extends 'articles/base.html' %}

{% block title %}CREATE{% endblock %}

{% block body %}
<h1 class="text-center">성공적으로 저장되었습니다</h1>
<a href="/articles/">BACK</a>
{% endblock %}

DJANGO_BLOG/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load static %}

{% block title %}DETAIL{% endblock %}
{% block body %}
<h1 class="text-center">DETAIL</h1>
<h2>{{ article.pk }}번 글</h2>
<hr>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
{% if article.image %}
<p>이미지 : <img src="{{ article.image.url }}" alt=""></p>
{% else %}
<p>이미지 : <img src="{% static 'articles/images/no.jpg' %}" alt=""></p>
{% endif %}

<p>작성시간 : {{ article.created_at }}</p>
<p>수정시간 : {{ article.updated_at }}</p>
<hr>
<form action="{% url 'articles:comment_create' article.id %}" method="POST">
    {% csrf_token %}
    <p>댓글 작성</p>
    <input type="text" name="content">
    <input type="submit" value="입력">
</form>
<h5>댓글 목록 | 현재 댓글수: {{ comments|length }}</h5>
{% for comment in comments %}
<ul>
    <li>
        {{ comment.content }}
        <form action="{% url 'articles:comment_delete' article.id comment.id %}" style="display: inline;" method = "POST">
            {% csrf_token %}
            <button class='btn btn-warning btn-sm'>삭제</button>
        </form>
    </li>
</ul>
{% empty %}
<p>댓글이 아직 없습니다.</p>
{% endfor %}

<hr>
<a href="{% url 'articles:index' %}" class="btn btn-primary">목록보기</a>
<a href="{% url 'articles:update' article.pk %}" class="btn btn-primary">수정하기</a>
<!-- <a href="{% url 'articles:delete' article.pk %}">[삭제하기]</a> -->
<form action="{% url 'articles:delete' article.pk %}", onclick="return confirm('R U Sure..??')" method='POST' style="display:inline">
    {% csrf_token %}
    <button class="btn btn-danger">삭제하기</button>
</form>
{% endblock %}

DJANGO_BLOG/articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% load static %}
{% block title %}EDIT{% endblock %}

{% block body %}
    <h1 class="class">EDIT</h1>
    <h2>{{ article.pk }}번 글</h2>
    <hr>
    {% if article.image %}
    <img src="{{ article.image.url }}" alt="">
    {% else %}
    <!-- <img src="{% static 'article/images/no.jpg' %}" alt=""> -->
    {% endif %}
    <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="title" value="{{ article.title }}"><br>
        <textarea name="content" id="" cols="30" rows="10">{{ article.content }}</textarea><br>
        <input type="text">
        <input type="file" name="image" accept="image/*">
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'articles:detail' article.pk %}">[이전으로]</a>
{% endblock %}

DJANGO_BLOG/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}

{% block title %}CRUD{% endblock %}

{% block body %}
<h1 class="text-center">Articles</h1>
<img src="{% static 'images/dog.jpg' %}" alt="sample" width='200px'><br>
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[NEW]</a>
{% else %}
<a href="{% url 'accounts:login' %">[새 글을 작성하려면 로그인하세요]</a>
{% endif %}
<hr>
{% for article in articles %}
    <p>No.{{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <!-- <p>글 내용 : {{ article.content }}</p> -->
    <a href="{% url 'articles:detail' article.pk %}">[글 상세보기]</a> | 작성자: {{article.user}}
    <hr>
{% endfor %}
{% endblock %}

DJANGO_BLOG/articles/templates/articles/new.html
{% extends 'articles/base.html' %}

{% block title %}NEW{% endblock %}

{% block body %}
<h1 class="text-center">NEW</h1>
<!-- action이 빈칸이면 자기 자신으로 요청을 함 -->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    제목 : <input type="text" name="title"><br>
    내용 : <textarea name="content" id="" cols="30" rows="10"></textarea><br>
    이미지 : <input type="file" name="image" accept="image/*">
    제출 : <input type="submit">
</form>
<hr>
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}