DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('doppelganger/', include('doppelganger.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGO_BLOG/doppelganger/urls.py
from django.urls import path
from . import views

app_name = 'doppelganger'

urlpatterns = [
    path('confirm', views.confirm, name="confirm"),
    path('', views.main, name="main"),    
]

DJANGO_BLOG/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

DJANGO_BLOG/doppelganger/models.py
from django.db import models

# Create your models here.
class Doppelganger(models.Model):
    name = models.CharField(max_length=10)
    address = models.TextField()
    job = models.CharField(max_length=30)

DJANGO_BLOG/doppelganger/views.py
from django.shortcuts import render
from faker import Faker
from .models import Doppelganger

# Create your views here.
def main(request):
    return render(request, 'doppelganger/main.html')

def confirm(request):
    # # DB에 이름이 있는지 확인
    # name = request.POST.get('name')
    # doppelganger = Doppelganger.objects.filter(name=name).first() #get()은 없을 경우 error 발생
    
    # #NULL이 아니면 True 반환
    # if doppelganger : 
    # else :
    
    fake = Faker('ko-KR')
    d_name = fake.name()
    d_job = fake.job()
    d_address = fake.address()
    
    doppelganger = Doppelganger(name=d_name, address=d_address, job=d_job)
    doppelganger.save()

    return render(request, 'doppelganger/confirm.html', {'doppelganger':doppelganger})

DJANGO_BLOG/doppelganger/templates/doppelganger/confirm.html
{% extends 'doppelganger/base.html '%}

{% block title %}도플갱어{%endblock%}

{% block body %}
    <h1 class="text-center">도플갱어</h1>
    <hr>
    
    <h3>도플갱어의 이름은 <span class="text-danger">{{ doppelganger.name }}입니다</span></h3>
    <h3>도플갱어는 현재 <span class="text-danger">{{ doppelganger.address }}에 살고 있습니다</span></h3>
    <h3>도플갱어의 직업은 <span class="text-danger">{{ doppelganger.job }}입니다</span></h3>
    <hr>
    <a href="{% url 'doppelganger:main' %}" class="btn btn-secondary">뒤로가기</a>
{% endblock %}

DJANGO_BLOG/doppelganger/templates/doppelganger/main.html
{% extends 'doppelganger/base.html '%}

{% block title %}도플갱어{%endblock%}

{% block body %}
    <h1 class="text-center">도플갱어</h1>
    <hr>
    <form action="{% url 'doppelganger:confirm' %}" method="POST">
        {% csrf_token %}
        너의 이름 : <input type="text" name="name"><br>
        <button class="btn btn-danger">도플갱어 확인하기</button>
    </form>
{% endblock %}